# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a6553cef73c7179d1d97ab9c5111f83"
name = "Maax - Seguimiento de pedidos"
handle = "maax-seguimiento-de-pedidos"
application_url = "https://shiny-zebra-pj6p69x7v569f49x-4040.app.github.dev"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://shiny-zebra-pj6p69x7v569f49x-4040.app.github.dev/auth/callback", "https://shiny-zebra-pj6p69x7v569f49x-4040.app.github.dev/auth/shopify/callback", "https://shiny-zebra-pj6p69x7v569f49x-4040.app.github.dev/api/auth/callback"]

[pos]
embedded = false
