[app]
name = "Maax - Seguimiento de pedidos"
handle = "maax-seguimiento-de-pedidos"
client_id = "2a6553cef73c7179d1d97ab9c5111f83"
client_secret = "8980ed13812139941d74355fdf42ff05"
scopes = "read_orders,read_customers"
redirect_url_whitelist = ["https://maax-shopify-track-app.onrender.com/api/auth/callback"]
application_url = "https://maax-shopify-track-app.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products" # ⚠️ OJO: esto no se está usando ahora

[auth]
redirect_urls = [
  "https://maax-shopify-track-app.onrender.com/api/auth/callback"
]

[pos]
embedded = false
